//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PosDatabaseEntities : DbContext
    {
        public PosDatabaseEntities()
            : base("name=PosDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<OrderItemTag> OrderItemTags { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<RoomManagement> RoomManagements { get; set; }
        public virtual DbSet<TableManagement> TableManagements { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
