//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemTag
    {
        public int id { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<int> TagId { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
