//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableManagement
    {
        public int Id { get; set; }
        public Nullable<int> TableNo { get; set; }
        public Nullable<int> NoOfChair { get; set; }
        public Nullable<int> RoomId { get; set; }
    
        public virtual RoomManagement RoomManagement { get; set; }
    }
}
